### PR TITLE
Extracted the prompt logic from qselect.cpp

### PR DESCRIPTION
**Pull request by voldyman**
this branch extracts the prompt rendering logic (mostly) from the qselect file so that it is easy to add functionality to the prompt like supporting other emacs style keybindings (ctrl-a, ctrl-e) etc.

### CODE REVIEW

**Comment by akojo** [comment]
Nice.
One nitpick, though. The existing code doesn't use "_" suffix for member variables so yours should neither.

**Comment by voldyman** [comment]
ah, ok. i was following the google's c++ style guide. fixed.

**Comment by akojo** [comment]
Hmm, please squash the commits. Also, I don't use `get_` -prefix for getter functions. (`Term::get_screen_size()` tries to follow the `ioctl` name 😄)

**Comment by voldyman** [comment]
what would you prefer instead of `get_query()`?

**Comment by akojo** [comment]
> what would you prefer instead of get_query()?

Just `query()`

**Comment by voldyman** [comment]
then it'll conflict with the member name

**Comment by akojo** [comment]
I know that then they'll conflict, but I personally prefer keeping the external interface as clean as possible. Also I like to follow the convention of C++ standard library, which also uses unadorned getters (e.g. `size()` instead of `get_size()`).

**Pull request merged**
