### PR TITLE
C++ modernization 

### PR DESCRIPTION
**Pull request by voldyman**
started using more C++ features like defining function types, avoiding pointers, using anonymous namespaces instead of static functions.

### CODE REVIEW

**Comment by voldyman** [comment]
updated the pull request to remove the commit that did the streaming print of result.

**Comment by akojo** [comment]
A couple of stylistic points first:

- I like the `using namespace std;` -idiom
- I'm not very fond of hiding types behind `using`-declarations (or `typedef`s for that matter)
- Unnamed namespaces do look nicer than `static` functions, I'll have to make a note to use them more in my code

I wrote `walk()` the way it is because I didn't want to create and destroy a new temporary `string` object for each file processed. So I just keep reusing the same memory area. Well, that and it's a nice trick, so I like to keep it around 😄.

BTW, strictly speaking `walk()` is no more `noexcept` after your changes since string concatenation may throw an exception (not that it matters in this case).

**Comment by akojo** [comment]
Oh, there's a typo in the commit message. Should be "modernisation"

**Comment by voldyman** [comment]
>I like the using namespace std; -idiom
oh, i didn't know that, i changed it because `using namespace std` pollutes the global namespace and introduces the possibility of name conflicts.

`using std::string` just make it clear which types are being imported from where, like you could later switch to a different implementation of string if need be without much hassle.

I understood that you had made the clever choice of updating the string in place but i find that right now the code is concise and clear but later on there might  be a possibility where one would accidentally access the wrong memory address and cause a segfault (in the best situation)
since the strings are small, creating a temporary objection shouldn't have much performance  impact, but i could implement the inplace thing using iterators if you want.

**Comment by akojo** [comment]
Well, these are pretty much issues of style, and in this case I like to stick with mine 😄

**Comment by voldyman** [comment]
updated the code to

* added back 'using namespace std'
* removed `using *`
* made the path replacement inplace, no new string objects.

**Comment by voldyman** [comment]
can i change something to get this merged? now there are no extra string object creations. [the harmful strcpy](http://stackoverflow.com/a/23317663/6645857) has been replaced with safe inplace iterator inserts.

**Pull request closed without merging**
